### ISSUE TITLE
Conditional Simulation

### ISSUE THREAD

**Issue by PaulMatlashewski** [JuliaEarth/SpectralGaussianSimulation.jl#3]
Is conditional simulation supported? I'm defining a conditional simulation problem and can successfully solve with a spectral Gaussian solver. However, the solution does not appear to respect my input data.

**Comment by juliohm** [comment]
It is not supported in this solver yet @PaulMatlashewski , we should probably raise a warning while it is not there. Could you submit a PR?

**Comment by juliohm** [comment]
Fixed by #4
